#!/usr/bin/env python3
"""Convert the vendored Spleen 5x8 BDF into the C glyph table the renderer links.

    python3 tools/make_font.py thirdparty/spleen/spleen-5x8.bdf arm9/source/font_spleen.h

The output is checked in, so the build needs nothing but the container. Re-run this only
when the font is updated, and commit what it produces.

Only ASCII 32-126 is emitted: 95 glyphs of 8 bytes, 760 bytes of ROM. The BDF carries 472
glyphs covering ISO10646-1, but wifi_slot_parse() already substitutes '?' for any SSID byte
outside 0x20-0x7E, so a glyph the decoder can never emit would be dead weight. Anything
outside the range is the renderer's problem, not this file's: fb_render.c maps it to a
fallback glyph rather than indexing past the end of the table.

Every glyph is verified to be exactly 5x8 with no bounding-box offset before anything is
written. Spleen is monospace (SPACING "C"), and this refuses to guess if that ever changes:
a converter that silently mis-positions a glyph produces a font that looks almost right.
"""
import re
import sys

FIRST = 0x20
LAST = 0x7E
WIDTH = 5
HEIGHT = 8
WANT_BBX = (WIDTH, HEIGHT, 0, -1)


def parse(path):
    """Return {codepoint: [8 row bytes]} for ASCII, or exit explaining what is wrong."""
    glyphs = {}
    enc = bbx = None
    bitmap = None

    for line in open(path, encoding="latin-1"):
        line = line.strip()

        if line.startswith("ENCODING"):
            enc = int(line.split()[1])
        elif line.startswith("BBX"):
            bbx = tuple(int(x) for x in line.split()[1:5])
        elif line == "BITMAP":
            bitmap = []
        elif line == "ENDCHAR":
            if bitmap is not None and enc is not None and FIRST <= enc <= LAST:
                if bbx != WANT_BBX:
                    sys.exit(f"glyph {enc} has BBX {bbx}, expected {WANT_BBX}. This font is "
                             f"not the uniform 5x8 the renderer assumes; positioning would "
                             f"have to be implemented before it could be used.")
                if len(bitmap) != HEIGHT:
                    sys.exit(f"glyph {enc} has {len(bitmap)} bitmap rows, expected {HEIGHT}")
                glyphs[enc] = bitmap
            bitmap = enc = bbx = None
        elif bitmap is not None and re.fullmatch(r"[0-9A-Fa-f]+", line):
            # A BDF row is padded to whole bytes and left-aligned, so bit 7 is the
            # leftmost pixel. At 5 wide that is one byte with the low 3 bits unused.
            row = int(line, 16)
            if len(line) != 2:
                sys.exit(f"expected one hex byte per row for a {WIDTH}px glyph, got {line!r}")
            if row & 0x07:
                sys.exit(f"glyph {enc} row {line!r} sets a bit outside the {WIDTH}px cell")
            bitmap.append(row)

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit(f"font is missing {len(missing)} ASCII glyphs, first is {missing[0]:#04x}")

    return glyphs


def emit(glyphs, out_path, src_path):
    count = LAST - FIRST + 1
    lines = [
        "// SPDX-License-Identifier: CC0-1.0",
        "//",
        "// GENERATED by tools/make_font.py -- do not edit by hand.",
        f"// Source: {src_path} (Spleen 5x8, BSD-2-Clause, see licenses/Spleen-BSD-2-Clause.txt)",
        "//",
        f"// ASCII {FIRST:#04x}-{LAST:#04x} only, {count} glyphs of {HEIGHT} bytes.",
        f"// Each byte is one row, bit 7 leftmost, low {8 - WIDTH} bits unused.",
        "",
        "#ifndef FONT_SPLEEN_H",
        "#define FONT_SPLEEN_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define FONT_FIRST      {FIRST:#04x}",
        f"#define FONT_LAST       {LAST:#04x}",
        f"#define FONT_GLYPH_W    {WIDTH}",
        f"#define FONT_GLYPH_H    {HEIGHT}",
        f"#define FONT_COUNT      {count}",
        "",
        "static const uint8_t font_spleen[FONT_COUNT * FONT_GLYPH_H] = {",
    ]

    for c in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{b:02X}" for b in glyphs[c])
        shown = chr(c) if c != 0x5C else "\\\\"
        lines.append(f"    {rows},  // {c:#04x} '{shown}'")

    lines += ["};", "", "#endif // FONT_SPLEEN_H", ""]
    open(out_path, "w").write("\n".join(lines))
    return count


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    glyphs = parse(src)
    n = emit(glyphs, dst, src)
    print(f"wrote {dst}: {n} glyphs, {n * HEIGHT} bytes of glyph data")


if __name__ == "__main__":
    main()
